config/routes.rb
Rails.application.routes.draw do

  # mount UeditorRails::Engine => '/ueditor'
  # post 'ueditor/file', :to => 'ueditor/assets#file'
  # post 'ueditor/image', :to => 'ueditor/assets#image'

   root 'home#index'

  resources :sessions
  resources :users
  delete '/logout' => 'sessions#destroy', as: :logout


  namespace :ancient  do
    get '/' => 'backyard#welcome'
    get 'index' => 'backyard#index'
    resources :articles do
      collection do
        get :art_catalog_index
      end
    end

  end



  namespace :agentback do
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
# -*- encoding : utf-8 -*-
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessor  :password, :password_confirmation

end

app/controllers/ancient/articles_controller.rb
class Ancient::ArticlesController <  BaseController

  def index
    @q = Article.ransack(params[:q])
    @articles =  @q.result.page(params[:page]).per(10)
  end

  def new
    @article = Article.new
  end

end

app/controllers/ancient/backyard_controller.rb
class Ancient::BackyardController <  BaseController

  def index
  end

  def welcome
    render layout: false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  def auth_user
    unless logged_in?
      flash[:notice] = "请登录"
      redirect_to new_session_path
    end
  end


end

app/controllers/base_controller.rb
class  BaseController < ApplicationController
  layout  'ancient'
  before_action :auth_user
  before_filter :load_resource





  def load_resource(class_name = nil, obj_name = nil)
    class_name ||= controller_name.singularize.classify
    return unless class_exists?(class_name)
    scope = class_name.constantize
    if ['new', 'create'].include?(params[:action].to_s)
      resource = scope.new
    elsif params[:id].to_i > 0
      resource = scope.find_by_id(params[:id])
      return rt_404 unless resource
    else
      resource = nil
    end
    obj_name ||= class_name.tableize.singularize
    instance_variable_set("@#{obj_name}", resource)
  end

  def class_exists?(class_name)
   klass = Module.const_get(class_name)
   return klass.is_a?(Class)
  rescue NameError
   return false
  end


end

app/controllers/home_controller.rb
class  HomeController < ApplicationController


   def index
   end


  def home
  end
end

app/controllers/logged_controller.rb
class  LoggedController < ApplicationController


end

app/controllers/sessions_controller.rb
class SessionsController < LoggedController

  def new

  end

  def create
    if user = login(params[:email], params[:password])
      #update_browser_uuid(user.uuid)
      flash[:notice] = "登陆成功"
      redirect_to root_path
    else
      flash[:notice] = "用户名或者密码不正确"
      redirect_to new_session_path
    end
  end

  def destroy
    logout
    cookies.delete :user_uuid
    flash[:notice] = "退出成功"
    redirect_to root_path
  end

end

app/controllers/ueditor/assets_controller.rb
# -*- encoding : utf-8 -*-

class Ueditor::AssetsController < ::ApplicationController

  before_filter :authenticate_user!
  # skip_before_filter :verify_authenticity_token

  def image
    unless params[:upfile]
      render json: {error: 1, message: "No File Selected!"}
      return
    end

    asset = ::Attachments::Image.new
    asset.data = params[:upfile]
    asset.set_assetable!(current_user.class.to_s, current_user.id)

    if asset.save!
      render json: {url: asset.data.url,
                    name: asset.store_name,
                    title: "pic",
                    original: asset.store_name,
                    state: "SUCCESS"}
    else
      render json: {state: "UNKNOWN"}
    end
  end

  def file
    unless params[:upfile]
      render json: {error: 1, message: "No File Selected!"}
      return
    end

    asset = ::Attachments::File.new
    asset.data = params[:upfile]
    asset.set_assetable! current_user.class.model_name, current_user.id

    if asset.save!
      render json: {url: asset.data.url,
                    name: asset.store_name,
                    title: "pic",
                    original: asset.store_name,
                    state: "SUCCESS"}
    else
      render json: {state: "UNKNOWN"}
    end
  end

end

app/controllers/users_controller.rb
class  UsersController < LoggedController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_param)
    #@user.uuid = session[:user_uuid]
    if @user.save
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end


  private

    def  user_param
      params.require(:user).permit(:email,:password,:password_confirmation,:loginname)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ancient/articles/_form.html.erb
<div>
  <h3><%= @article.new_record? ? "新增文章" : "修改文章" %></h3>
</div>
<div class="form-body">
  <%=simple_form_for @article,
    url: (@article.new_record? ? ancient_articles_path : ancient_article_path(@article)),
    method: (@article.new_record? ? 'post' : 'put'),
    html: { class: 'form-horizontal' } do |f| %>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">文章题目：*</label>
      <div class="col-sm-5">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="abstract" class="col-sm-2 control-label">摘要：*:</label>
      <div class="col-sm-5">
        <%= f.text_field :abstract, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <label for="content" class="col-sm-2 control-label">文章详情：*</label>
      <div class="col-sm-5">
        <%= f.text_area :content, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= f.submit (@article.new_record? ? "新建文章" : "编辑文章"), class: "btn btn-default" %>
      </div>
    </div>
  <% end -%>
</div>

app/views/ancient/articles/_search.html.erb
<%=search_form_for @q, :url => ancient_articles_path ,:html => {:method => :get, :class => "well form-search"}  do |f| %>
  <span>名称：<%= f.text_field :name_cont %></span>
  <%= render "ancient/shared/search_bottom", :f => f %>
<% end %>

app/views/ancient/articles/edit.html.erb
<%=render 'form'%>

app/views/ancient/articles/index.html.erb
<div class="ibox">
  <div class="ibox-title">
    <h5>文章管理</h5>
  </div>
  <div class="ibox-content">
    <%= render "search" %>
    <div class="page-header">
      <%= link_to '新增文章', new_ancient_article_path(:back => request.fullpath), :class => "btn btn-sm btn-primary" %>
    </div>
    <table class="table table-bordered table-striped table-hover">
      <tr>
        <th class="tc">序号</th>
        <th class="tc">文章名称</th>
        <th class="tc">文章分类</th>
        <th class="tc">发布人</th>
        <th class="tc">发布时间</th>
        <th class="tc">操作</th>
      </tr>
      <% @articles.each_with_index do |article, index| %>
        <tr>
          <td class="textc"><%= index + 1%></td>
          <td><%= article.name %></td>
          <td><%= article.catalog.name %></td>
          <td><%= article.user_name %></td>
          <td><%= article.created_at %></td>
          <td class="tc">
            <% edit_link = link_to '修改', edit_ancient_article_path(article, :back => request.fullpath)%>
            <% destroy_link = link_to '删除', ancient_article_path(article, :back => request.fullpath), :method => :delete, data: { confirm: '確定要刪除吗?' }%>
            <%= operate_buttons([edit_link, destroy_link].compact) %>
          </td>
        </tr>
      <% end -%>
    </table>
    <%= paginate @articles %>
  </div>
</div>

app/views/ancient/articles/new.html.erb
<%=render 'form'%>

app/views/ancient/backyard/index.html.erb
    <div class="col-sm-12">
        <blockquote class="text-warning" style="font-size:14px">
          您是否需要自己做一款后台、会员中心等等的，但是又缺乏html等前端知识…
            <br>您是否一直在苦苦寻找一款适合自己的后台主题…
            <br>您是否想做一款自己的web应用程序…
            <br>…………
            <h4 class="text-danger">那么，现在H+来了</h4>
        </blockquote>

        <hr>
    </div>
    <div class="col-sm-3">
        <h2>Hello,Guest</h2>
        <small>移动设备访问请扫描以下二维码：</small>
        <br>
        <br>
        <img src="img/qr_code.png" width="100%" style="max-width:264px;">
        <br>
    </div>
    <div class="col-sm-5">
        <h2>
                        H+ 后台主题UI框架
                    </h2>
        <p>H+是一个完全响应式，基于Bootstrap3.3.6最新版本开发的扁平化主题，她采用了主流的左右两栏式布局，使用了Html5+CSS3等现代技术，她提供了诸多的强大的可以重新组合的UI组件，并集成了最新的jQuery版本(v2.1.4)，当然，也集成了很多功能强大，用途广泛的jQuery插件，她可以用于所有的Web应用程序，如<b>网站管理后台</b>，<b>网站会员中心</b>，<b>CMS</b>，<b>CRM</b>，<b>OA</b>等等，当然，您也可以对她进行深度定制，以做出更强系统。</p>
        <p>
            <b>当前版本：</b>v4.1.0
        </p>
        <p>
            <b>定价：</b><span class="label label-warning">&yen;988（不开发票，不议价）</span>
        </p>
        <br>
        <p>
            <a class="btn btn-success btn-outline" href="http://wpa.qq.com/msgrd?v=3&amp;uin=516477188&amp;site=qq&amp;menu=yes" target="_blank">
                <i class="fa fa-qq"> </i> 联系我
            </a>
            <a class="btn btn-white btn-bitbucket" href="http://www.zi-han.net/" target="_blank">
                <i class="fa fa-home"></i> 访问博客
            </a>
        </p>
    </div>
    <div class="col-sm-4">
        <h4>H+具有以下特点：</h4>
        <ol>
            <li>完全响应式布局（支持电脑、平板、手机等所有主流设备）</li>
            <li>基于最新版本的Bootstrap 3.3.6</li>
            <li>提供3套不同风格的皮肤</li>
            <li>支持多种布局方式</li>
            <li>使用最流行的的扁平化设计</li>
            <li>提供了诸多的UI组件</li>
            <li>集成多款国内优秀插件，诚意奉献</li>
            <li>提供盒型、全宽、响应式视图模式</li>
            <li>采用HTML5 & CSS3</li>
            <li>拥有良好的代码结构</li>
            <li>更多……</li>
        </ol>
    </div>

app/views/ancient/backyard/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="renderer" content="webkit">
      <meta http-equiv="Cache-Control" content="no-siteapp" />
      <title>昔阳县国税局税收风险控制分析管理系统</title>

      <!--[if lt IE 9]>
      <meta http-equiv="refresh" content="0;ie.html" />
      <![endif]-->

      <%= stylesheet_link_tag  'ancient_out' %>
      <%= javascript_include_tag 'ancient_out' %>
  </head>
<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span><img alt="image" class="img-circle" src="img/profile_small.jpg" /></span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                               <span class="block m-t-xs"><strong class="font-bold">Beaut-zihan</strong></span>
                                <span class="text-muted text-xs block">超级管理员</span>
                                </span>
                            </a>
                        </div>
                        <div class="logo-element">H+
                        </div>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">文章设置</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="<%=ancient_articles_path%>">文章列表</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="index_v2.html">主页示例二</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="index_v3.html">主页示例三</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="index_v4.html">主页示例四</a>
                            </li>
                            <li>
                                <a href="index_v5.html" target="_blank">主页示例五</a>
                            </li>
                        </ul>

                    </li>
                    <li>
                        <a href="#"><i class="fa fa-edit"></i> <span class="nav-label">表单</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="form_basic.html">基本表单</a>
                            </li>
                            <li><a class="J_menuItem" href="form_validate.html">表单验证</a>
                            </li>
                            <li><a class="J_menuItem" href="form_advanced.html">高级插件</a>
                            </li>
                            <li><a class="J_menuItem" href="form_wizard.html">表单向导</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <ul class="nav navbar-top-links navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-envelope"></i> <span class="label label-warning">16</span>
                            </a>
                            <ul class="dropdown-menu dropdown-messages">
                                <li class="m-t-xs">
                                    <div class="dropdown-messages-box">
                                        <a href="profile.html" class="pull-left">
                                            <img alt="image" class="img-circle" src="img/a7.jpg">
                                        </a>
                                        <div class="media-body">
                                            <small class="pull-right">46小时前</small>
                                            <strong>小四</strong> 这个在日本投降书上签字的军官，建国后一定是个不小的干部吧？
                                            <br>
                                            <small class="text-muted">3天前 2014.11.8</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="dropdown-messages-box">
                                        <a href="profile.html" class="pull-left">
                                            <img alt="image" class="img-circle" src="img/a4.jpg">
                                        </a>
                                        <div class="media-body ">
                                            <small class="pull-right text-navy">25小时前</small>
                                            <strong>国民岳父</strong> 如何看待“男子不满自己爱犬被称为狗，刺伤路人”？——这人比犬还凶
                                            <br>
                                            <small class="text-muted">昨天</small>
                                        </div>
                                    </div>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a class="J_menuItem" href="mailbox.html">
                                            <i class="fa fa-envelope"></i> <strong> 查看所有消息</strong>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                                <i class="fa fa-bell"></i> <span class="label label-primary">8</span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                                <li>
                                    <a href="mailbox.html">
                                        <div>
                                            <i class="fa fa-envelope fa-fw"></i> 您有16条未读消息
                                            <span class="pull-right text-muted small">4分钟前</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="profile.html">
                                        <div>
                                            <i class="fa fa-qq fa-fw"></i> 3条新回复
                                            <span class="pull-right text-muted small">12分钟钱</span>
                                        </div>
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div class="text-center link-block">
                                        <a class="J_menuItem" href="notifications.html">
                                            <strong>查看所有 </strong>
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="hidden-xs">
                            <a href="index_v1.html" class="J_menuItem" data-index="0"><i class="fa fa-cart-arrow-down"></i> 购买</a>
                        </li>
                        <li class="dropdown hidden-xs">
                            <a class="right-sidebar-toggle" aria-expanded="false">
                                <i class="fa fa-tasks"></i> 主题
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="row content-tabs">
              <button class="roll-nav roll-left J_tabLeft navbar-minimalize"><i class="fa fa-backward"></i>
             </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <a href="javascript:;" class="active J_menuTab" data-id="index.html">首页</a>
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight"><i class="fa fa-forward"></i>
                </button>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">关闭操作<span class="caret"></span>
                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive"><a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <li class="J_tabCloseAll"><a>关闭全部选项卡</a>
                        </li>
                        <li class="J_tabCloseOther"><a>关闭其他选项卡</a>
                        </li>
                    </ul>
                </div>
                <a href="login.html" class="roll-nav roll-right J_tabExit"><i class="fa fa fa-sign-out"></i> 退出</a>
            </div>
            <div class="row J_mainContent" id="content-main">
              <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="<%=ancient_index_path%>"  frameborder="0" data-id="index.html" seamless>
              </iframe>
            </div>
            <div class="footer">
                <div class="pull-right">&copy; 2014-2015 <a href="http://www.zi-han.net/" target="_blank">zihan's blog</a>
                </div>
            </div>
        </div>
        <!--右侧部分结束-->
    </div>

 </body>
</html>

app/views/ancient/shared/_search_bottom.html.erb
<button class="btn btn-info btn-sm" type="submit">查 询</button>
<button class="btn btn-info btn-sm" onclick='window.location.href=$(".form-search").attr("action");; return false;'>全部</button>
<span>总共：<%= @q.result.count %>条</span>

app/views/home/_content.html.erb
  <div class="container marketing">
  <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">
    </div>

app/views/layouts/ancient.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--360浏览器优先以webkit内核解析-->
    <title>H+ 后台主题UI框架 - 主页示例</title>
    <%= stylesheet_link_tag  'ancient' %>
    <%= javascript_include_tag 'ancient' %>
</head>
<body class="gray-bg">
    <div class="row  border-bottom white-bg dashboard-header">
      <%= yield %>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>昔阳县国税局税收风险控制分析管理系统</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
   <%= stylesheet_link_tag "application" %>

     <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="http://cdn.bootcss.com/bootswatch/3.3.7/flatly/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="navbar-wrapper">
   <div class="container">
    <%= render 'shared/banner'%>
   </div>
  </div>
   <%= yield %>
   <%= render 'shared/foot'%>
</body>
</html>

app/views/layouts/logged.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>昔阳县国税局税收风险控制分析管理系统</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag  'login', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
  <body class="login_body">
   <div class="h100"></div>
     <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
  <div class="navbar-header">
    <a href="<%=root_path%>" class="navbar-brand">昔阳县国税局风控系统</a>
    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
    <div class="navbar-collapse collapse" id="navbar-main">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">税收政策<span class="caret"></span></a>
        <ul class="dropdown-menu" aria-labelledby="themes">
          <li><a href="../yeti/">Yeti</a></li>
        </ul>
      </li>
      <li>
        <a href="../help/">税收知识</a>
      </li>
      <li>
        <a href="http://news.bootswatch.com">税收新闻</a>
      </li>
      <li class="dropdown">
        <a href="http://news.bootswatch.com">关于我们</a>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%unless  logged_in? %>
        <li><a href="<%=new_user_path%>" target="_blank">注册</a></li>
        <li><a href="<%=new_session_path%>" target="_blank">登陆</a></li>
      <%else%>
        <li><a href="#">欢迎你, <%= current_user.name %></a></li>
        <li><%=link_to  '后台管理', ancient_path  %></li>
        <li><%= link_to "退出", logout_path, method: :delete %></li>
      <%end%>
    </ul>
  </div>
  </div>
</nav>